pipeline {
    agent any
    environment {
        DOCKER_HUB_CREDENTIALS = credentials('dockerhub-credentials')
        DOCKER_IMAGE = "roqiaahmed447141/messaging_app"
        DJANGO_SECRET_KEY = credentials('django-secret-key')
        MYSQL_DB = credentials('MYSQL_DB')
        DATABASE_USERNAME = credentials('DATABASE_USERNAME')
        DATABASE_PASSWORD = credentials('DATABASE_PASSWORD')
        DATABASE_ROOT_PASSWORD = credentials('DATABASE_ROOT_PASSWORD')
        DATABASE_ENGINE = credentials('DATABASE_ENGINE')
        DATABASE_HOST = credentials('DATABASE_HOST')
        DATABASE_PORT = credentials('DATABASE_PORT')
        
        
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-credentials',
                    url: 'https://github.com/roqiaahmed/alx-backend-python.git'
            }
        }
        
        stage('Build') {
            steps {
                echo 'Building..'
                sh '''
                cd messaging_app
                pip3 install -r requirements.txt
                '''
            }
        }
        
        stage('Test') {
            steps {
                echo 'Testing..'
                sh '''
                cd messaging_app
                pytest
                '''
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t $DOCKER_IMAGE:latest -f messaging_app/Dockerfile ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    sh "echo $DOCKER_HUB_CREDENTIALS | docker login -u roqiaahmed447141 --password-stdin"
                    sh "docker push $DOCKER_IMAGE:latest"
                }
            }
        }
    }
}
