pipeline {
    agent {
        docker { image 'python:3' }
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-credentials',
                    url: 'https://github.com/roqiaahmed/alx-backend-python.git'
            }
        }
        stage('Test') {
            steps {
                sh 'pip --version'
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                sh '''
                cd messaging_app
                pip3 install -r requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                sh '''
                cd messaging_app
                pytest
                '''
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
