name: Docker Build & Push

on:
  push:
    branches: ["main"] # Only build/push when pushing to main
  workflow_dispatch: # Allow manual trigger

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: messaging_app/Dockerfile
          push: true
          tags: roqiaahmed447141/messaging_app:latest
