services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost","-p${DATABASE_ROOT_PASSWORD}"]
      interval: 5s
      retries: 10
      start_period: 5s
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql


  web:
    build: . 
    container_name: messaging-app-image
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${MYSQL_DB}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    env_file:
      - .env

  # migrate:
  #   build: .
  #   command: python manage.py migrate
  #   depends_on:
  #     - db
volumes:
  db_data:
    name: messaging_app_data