apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: messaging
    version: blue # start with blue deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
