# Generated by Django 5.2.4 on 2025-07-22 17:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(default=uuid.UUID('5429de0e-f258-4769-a226-4ed2e3cbc323'), editable=False, primary_key=True, serialize=False),
        ),
    ]
