# Generated by Django 5.2.4 on 2025-07-24 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_conversation_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(default=uuid.UUID('81c86edc-6464-4cc3-8ad1-915adf8377a3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
