# Generated by Django 5.2.4 on 2025-07-24 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_conversation_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(default=uuid.UUID('ae90524b-0fd5-486d-be21-5e943d480f4c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
