# Generated by Django 5.2.4 on 2025-07-24 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_conversation_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(default=uuid.UUID('40a15b2c-933b-492f-833e-52fcf7c3ca3d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
