# Generated by Django 5.2.4 on 2025-07-24 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_conversation_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(default=uuid.UUID('a71cdfba-a7b7-45d8-b585-e4a8f483543d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
