# Generated by Django 5.2.4 on 2025-07-25 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_conversation_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(default=uuid.UUID('e10f6975-70a8-4bec-b813-091be788fd12'), editable=False, primary_key=True, serialize=False),
        ),
    ]
