# Generated by Django 5.2.4 on 2025-07-26 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_conversation_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(default=uuid.UUID('ea9c1fe8-29be-498b-b8e8-447b280defaa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
