# Generated by Django 5.2.4 on 2025-07-26 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_alter_conversation_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('clint', 'Clint')], default='clint', max_length=50),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(default=uuid.UUID('44dbb1a5-dbca-48ea-bfe0-75450518d69f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
